In [18]:
import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import pickle

In [43]:
#loading the dataset
df = pd.read_csv(r'C:\Users\HARSH\Desktop\Project_Parade\datasets\updated_project_recommendation_extended.csv')
df.head(10)

skill1           skill2           skill3          skill4  \
0     TensorFlow            Flask              C++  Bioinformatics   
1           Java              SQL           Python      Blockchain   
2  Deep Learning              C++       Blockchain          Django   
3            C++    Deep Learning  Ethical Hacking      TensorFlow   
4        PyTorch           Pandas       Middleware            RTOS   
5         DevOps           Django       Embedded C      JavaScript   
6          React   Bioinformatics           DevOps             SQL   
7         Docker  Computer Vision  Cloud Computing          OpenCV   
8   Cryptography          MongoDB       TensorFlow      Kali Linux   
9        Node.js           Docker             RTOS          Pandas   

          skill5           skill6                        project_name  
0         Django           Docker  AI-Powered Legal Document Analysis  
1     Metasploit     Cryptography         Self-Driving Car Simulation  
2   Cryptography  Cloud Computing              Stock Price Prediction  
3          React          MongoDB             IoT-Based Smart Farming  
4     Embedded C               AI        Reinforcement Learning Agent  
5            C++  Smart Contracts            Blockchain Voting System  
6          NumPy              AWS        Automated Code Review System  
7     Kubernetes              C++           Disease Prediction System  
8   Data Science       Kubernetes       Cybersecurity Threat Detector  
9  Deep Learning           Python             Text Summarization Tool

In [44]:
df.isna().sum()

skill1          0
skill2          0
skill3          0
skill4          0
skill5          0
skill6          0
project_name    0
dtype: int64

In [45]:
df['skill4'].unique()

array(['Bioinformatics', 'Blockchain', 'Django', 'TensorFlow', 'RTOS',
       'JavaScript', 'SQL', 'OpenCV', 'Kali Linux', 'Pandas',
       'Metasploit', 'AI', 'DevOps', 'Flask', 'Cryptography', 'NumPy',
       'Data Science', 'MongoDB', 'Java', 'Penetration Testing', 'IoT',
       'PyTorch', 'Python', 'Docker', 'C', 'C++', 'Kubernetes', 'FastAPI',
       'Node.js', 'React', 'Julia', 'Elasticsearch', 'Vue.js', 'Dart',
       'Firebase', 'Fortran', 'CUDA', 'COBOL', 'RabbitMQ', 'Assembly',
       'Ansible', 'F#', 'TypeScript', 'Redux', 'MATLAB', 'NLP', 'GraphQL',
       'PySpark', 'Power BI', 'Neo4j', 'HBase', 'Perl', 'Prolog',
       'Next.js', 'Jenkins'], dtype=object)

In [46]:
#Encoding part
le = LabelEncoder()
df['skill1'] = le.fit_transform(df['skill1'])
df['skill2'] = le.fit_transform(df['skill2'])
df['skill3'] = le.fit_transform(df['skill3'])
df['skill4'] = le.fit_transform(df['skill4'])
df['skill5'] = le.fit_transform(df['skill5'])
df['skill6'] = le.fit_transform(df['skill6'])


df['project_name'] = le.fit_transform(df['project_name'])
df.head(5)

skill1  skill2  skill3  skill4  skill5  skill6  project_name
0      49      20       6       3      12      17            22
1      22      50      43       4      30      10            43
2       9       5       4      13       8       8            50
3       4      11      14      52      44      35            40
4      38      40      33      47      15       0            42

In [47]:
df['skill4'].unique()

array([ 3,  4, 13, 52, 47, 25, 51, 38, 28, 39, 31,  0, 12, 19,  9, 37, 11,
       32, 24, 40, 23, 45, 46, 14,  5,  6, 29, 17, 36, 49, 27, 15, 54, 10,
       18, 20,  8,  7, 48,  2,  1, 16, 53, 50, 30, 33, 21, 44, 42, 34, 22,
       41, 43, 35, 26])

In [130]:
# dataset spliting into two parts, features and target columns
X = df[['skill1','skill2','skill3','skill4','skill5','skill6']]
y = df['project_name'] #label or targer variable

In [131]:
#####  train_size is 80%, keep aside 20% as testing data   #####
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
###### Decison Tree classifier ############

In [132]:
model = DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [133]:
# test the model
y_pred = model.predict(X_test)
print(y_pred)

[22 31 41 ... 22 51  6]


In [134]:
# model accuracy 
print(accuracy_score(y_test,y_pred))

0.9900793650793651


In [135]:
# Confusion metrics 
print(confusion_matrix(y_test,y_pred))

[[35  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 39  0  0]
 [ 0  0  0 ...  0 36  0]
 [ 0  0  0 ...  0  0 42]]


In [136]:
##### Random Forest ##############

In [137]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train,y_train)

RandomForestClassifier()

In [138]:
#test the model
y_pred = rf_model.predict(X_test)
print(y_pred)

[22 31 41 ... 22 51  6]


In [139]:
print(accuracy_score(y_test,y_pred))

0.9900793650793651


In [140]:
print(confusion_matrix(y_test,y_pred))

[[35  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 33 ...  0  0  0]
 ...
 [ 0  0  0 ... 39  0  0]
 [ 0  0  0 ...  0 36  0]
 [ 0  0  0 ...  0  0 42]]


In [141]:
#### after Dropping skill5, skill6  #########

In [60]:
#loading the dataset
df = pd.read_csv(r'C:\Users\HARSH\Desktop\Project_Parade\datasets\updated_project_recommendation_extended.csv')
df.head(10)

skill1           skill2           skill3          skill4  \
0     TensorFlow            Flask              C++  Bioinformatics   
1           Java              SQL           Python      Blockchain   
2  Deep Learning              C++       Blockchain          Django   
3            C++    Deep Learning  Ethical Hacking      TensorFlow   
4        PyTorch           Pandas       Middleware            RTOS   
5         DevOps           Django       Embedded C      JavaScript   
6          React   Bioinformatics           DevOps             SQL   
7         Docker  Computer Vision  Cloud Computing          OpenCV   
8   Cryptography          MongoDB       TensorFlow      Kali Linux   
9        Node.js           Docker             RTOS          Pandas   

          skill5           skill6                        project_name  
0         Django           Docker  AI-Powered Legal Document Analysis  
1     Metasploit     Cryptography         Self-Driving Car Simulation  
2   Cryptography  Cloud Computing              Stock Price Prediction  
3          React          MongoDB             IoT-Based Smart Farming  
4     Embedded C               AI        Reinforcement Learning Agent  
5            C++  Smart Contracts            Blockchain Voting System  
6          NumPy              AWS        Automated Code Review System  
7     Kubernetes              C++           Disease Prediction System  
8   Data Science       Kubernetes       Cybersecurity Threat Detector  
9  Deep Learning           Python             Text Summarization Tool

In [61]:
df.drop(columns=['skill5', 'skill6'], axis=1,inplace=True)

In [62]:
df['project_name']

0         AI-Powered Legal Document Analysis
1                Self-Driving Car Simulation
2                     Stock Price Prediction
3                    IoT-Based Smart Farming
4               Reinforcement Learning Agent
                        ...                 
5035               AI-Based Crime Prediction
5036        AI-Powered Code Review Assistant
5037    AI-Based Intelligent Tutoring System
5038    AI-Powered Financial Fraud Detection
5039    AI-Based Real-Time Emotion Detection
Name: project_name, Length: 5040, dtype: object

In [66]:
df['project_name'].unique()


array(['AI-Powered Legal Document Analysis',
       'Self-Driving Car Simulation', 'Stock Price Prediction',
       'IoT-Based Smart Farming', 'Reinforcement Learning Agent',
       'Blockchain Voting System', 'Automated Code Review System',
       'Disease Prediction System', 'Cybersecurity Threat Detector',
       'Text Summarization Tool', 'Social Media Sentiment Tracker',
       'Automated Resume Screener', 'AI-Based Fraud Detection',
       'Image Caption Generator', 'Face Recognition System',
       'AI Virtual Assistant', 'AI-Powered Health Diagnosis',
       'Speech Emotion Recognition', 'AI-Based Music Recommendation',
       'Stock Market Trend Analysis', 'AI-Based Customer Support',
       'Hand Gesture Recognition', 'AI-Powered Personal Finance Advisor',
       'AI-Generated Art System', 'AI-Powered Hiring System',
       'AI-Powered Resume Generator', 'Medical Image Analysis',
       'Fake News Detection', 'Sentiment Analysis',
       'Drowsiness Detection System', 'Smart 

In [67]:
# Encoding part converting all categorical data into numeric

le = LabelEncoder()
df['skill1'] = le.fit_transform(df['skill1'])
df['skill2'] = le.fit_transform(df['skill2'])
df['skill3'] = le.fit_transform(df['skill3'])
df['skill4'] = le.fit_transform(df['skill4'])


df['project_name'] = le.fit_transform(df['project_name'])
df.head(5)

skill1  skill2  skill3  skill4  project_name
0      49      20       6       3            22
1      22      50      43       4            43
2       9       5       4      13            50
3       4      11      14      52            40
4      38      40      33      47            42

In [68]:
df['project_name'].unique()

array([22, 43, 50, 40, 42, 31, 29, 34, 33, 51, 47, 30,  6, 39, 36,  0, 20,
       48, 11, 49,  4, 38, 25, 15, 21, 26, 41, 37, 44, 35, 46, 14, 10, 45,
        8,  9, 18, 32, 12, 23, 28, 24,  3,  5, 16,  7, 27, 17, 13,  1,  2,
       19])

In [144]:
#dataset spliting into two parts, features and target columns
X = df[['skill1','skill2','skill3','skill4']] # features
y = df['project_name'] # targer variable

In [145]:
#####  train_size is 80%, keep aside 20% as testing data   #####
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [146]:
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [147]:
#test the model
y_pred = dt_model.predict(X_test)
print(y_pred)

[22 31 41 ... 22 51  6]


In [148]:
print(accuracy_score(y_test,y_pred))

0.9890873015873016


In [149]:
print(confusion_matrix(y_test,y_pred))

[[35  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 33 ...  0  0  0]
 ...
 [ 0  0  0 ... 39  0  0]
 [ 0  0  0 ...  0 36  0]
 [ 0  0  0 ...  0  0 42]]


In [151]:
# Saving model using pickle
with open(r'C:\Users\HARSH\Desktop\Project_Parade\dt_model.pkl', 'wb') as model_file:
    pickle.dump(dt_model, model_file)